### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon2#1]
#### The poseidon2 package format and the .janno file
- [ ] Finish the definition of the .janno file structure/content
- [x] Create a comprehensive, open, git observed documentation (and therefore a standard) of the poseidon2 package format and the .janno file based on the README [here](https://github.com/poseidon-framework/poseidon2.package.manager), the relevant fragments in the palaeowiki and the .janno google docs sheet.

#### Department procedures
- [x] Come up with a workflow to get data into the poseidon2 format
- [x] Identify features the poseidon2 cli tool should provide to make this as easy as possible

#### The poseidon2 R package/cli tool

- [ ] Identify necessary features beyond the core abilities already implemented (merge, validate, convert plink-binary2eigenstrat)
- [x] Make a design decision: Is a cli tool based on R fine? Should we try to separate R functionality and cli functionality as we did with sidora (I would argue that we do not have to)? Should we reimplement with yet another language/framework to be more elegant and maybe future-proof (Haskell)?
- [x] Write proper documentation (including DESCRIPTION, README and at least a quickstart guide)
- [ ] Atomize the current code and write unit tests
- [ ] Test and review the code to make it very robust
- [ ] Decide when input validation should stop the program and when it should only inform the user
- [ ] Invent more sophisticated test data
- [x] Simplify the cluster setup and find a way to automate the sbatch call
- [x] Activate CD/CI testing
- [x] Automate installation (and maybe cluster deployment)
- [x] Document not just the R dependencies, but also the system requirements
- [ ] ~Make the anno2janno transformation module available and sufficiently generic and robust to work with most anno files out there. At least on a basic level~
- [x] Add validation for .bed, .bim and .fam files
- [x] Make the software fully independent of our cluster architecture and allow for calls to local software
- [x] Provide the whole package with system dependencies (including plink etc.) in a docker container or similar

**Comment by stschiff** [comment]
GO HASKELL!

**Comment by stschiff** [comment]
But seriously, thanks for this list. Very comprehensive, indeed. I think with respect to tooling, I would vote for not tying ourselves too closely into R. It's totally OK to have the first CLI tooling to be provided for working with this data based on your R CLI, and it's very well possible that this will remain the main tool for a while, but given the standard is well defined, I'd be looking forward to invest some time in other programming languages as well. But that can go secondary.

**Comment by nevrome** [comment]
Ja. Haskell would actually be a good choice for all these parsing and validation operations. And I would really like to have an excuse to work with it. 
But I'm much faster with R and we already established a CLI setup with it for sidora recently. Also a lot more people can read and write it.

**Comment by nevrome** [comment]
Outdated - all of this DID go to Haskell eventually.
